[package]
name = "uniffi_bindgen"
version = "0.28.2"
description = "a multi-language bindings generator for rust (codegen and cli tooling)"
documentation = "https://mozilla.github.io/uniffi-rs"
homepage = "https://mozilla.github.io/uniffi-rs"
repository = "https://github.com/mozilla/uniffi-rs"
license = "MPL-2.0"
edition = "2021"
keywords = ["ffi", "bindgen"]
readme = "../README.md"

[features]
default = ["cargo-metadata"]
cargo-metadata = ["dep:cargo_metadata"]
bindgen-tests = ["cargo-metadata", "dep:uniffi_testing"]
ffi-trace = ["uniffi_testing?/ffi-trace"]

[dependencies]
anyhow =  { workspace = true }
camino = { workspace = true }
cargo_metadata = { workspace = true, optional = true }
fs-err = { workspace = true }
glob = { workspace = true }
goblin = { workspace = true }
heck = { workspace = true }
once_cell = { workspace = true }
paste = { workspace = true }
rinja = { workspace = true, features = ["config"] }
serde = { workspace = true, features = ["derive"] }
# Don't include the `unicode-linebreak` or `unicode-width` since that functionality isn't needed for
# docstrings.
textwrap = { workspace = true, features=["smawk"] }
toml = { workspace = true }
uniffi_meta = { workspace = true }
uniffi_testing = { workspace = true, optional = true }
uniffi_udl = { workspace = true }
